enable_rgb = true
import = ["/home/andy/.config/alacritty/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 11

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 5

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/bash"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
y = 10

[footer_bar]
footer_bar = { foreground = '#CDD6F4', background = '#1E1E2E' }
