#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/alacritty
rm -rf $HOME/.config/polybar
rm -rf $HOME/.config/nvim
rm -rf $HOME/.config/tmux
rm -rf $HOME/.config/phpactor

ln -s $DOTFILES/alacritty $HOME/.config/alacritty
ln -s $DOTFILES/polybar $HOME/.config/polybar
ln -s $DOTFILES/nvim $HOME/.config/nvim
ln -s $DOTFILES/tmux $HOME/.config/tmux
ln -s $DOTFILES/phpactpr $HOME/.config/phpactor
